### ISSUE TITLE
web message only gets send

### ISSUE THREAD

**Issue by zezo357** [vursin/isolate_manager#2]
[Isolate Contactor]: Initialized
[Isolate Contactor]: Message send to isolate: {password: 123456, userHandle: username}

i can never get result 

do you know a way to check if the web worker is loaded probably or not?

**Comment by zezo357** [comment]
even the original code doesnt send anything back
```
// ignore_for_file: avoid_web_libraries_in_flutter, depend_on_referenced_packages

import 'dart:async';
import 'dart:convert';
import 'dart:html' as html;
import 'dart:js' as js;

import 'package:js/js.dart' as pjs;
import 'package:js/js_util.dart' as js_util;

@pjs.JS('self')
external dynamic get globalScopeSelf;

// dart compile js lib/common/functionName.dart -o functionName.js

main() {
  callbackToStream('onmessage', (html.MessageEvent e) {
    return js_util.getProperty(e, 'data');
  }).listen((message) async {
    // TODO: Function for computation here
    final result = await functionName(message);

    jsSendMessage(result);
  });
}

/// Modify your function here
dynamic functionName(dynamic message) => message;

Stream<T> callbackToStream<J, T>(
    String name, T Function(J jsValue) unwrapValue) {
  var controller = StreamController<T>.broadcast(sync: true);
  js_util.setProperty(js.context['self'], name, js.allowInterop((J event) {
    controller.add(unwrapValue(event));
  }));
  return controller.stream;
}

void jsSendMessage(dynamic m) {
  js.context.callMethod('postMessage', [jsonEncode(m)]);
}```


and i did put it in web folder


this is how i call it 

```
     IsolateManager isolateContactor1 = IsolateManager.createOwnIsolate(
      isDebug: true,
   functionName,
     workerName: 'functionName'
    );
    await isolateContactor1.start();
     print(await isolateContactor1.sendMessage({"data":"alot of data"}));

```

**Comment by vursin** [comment]
I think the issue was caused because `final result = await functionName(message);` no need to `await` if it isn't a `Future`, so you can use `Completer` to make it works in both cases.

You could try to change the code inside functionName.dart from
``` dart
main() {
  callbackToStream('onmessage', (html.MessageEvent e) {
    return js_util.getProperty(e, 'data');
  }).listen((message) async {
    // TODO: Function for computation here
    final result = await functionName(message);

    jsSendMessage(result);
  });
}
```
to
``` dart
main() {
  callbackToStream('onmessage', (html.MessageEvent e) {
    return js_util.getProperty(e, 'data');
  }).listen((message) async {
    // TODO: Function for computation here
    final Completer completer = Completer();
    completer.future.then((value) => jsSendMessage(value));
    completer.complete(functionName(message));
  });
}
```

**Comment by zezo357** [comment]
> @zezo357 I think the issue was caused because `final result = await functionName(message);` no need to `await` if it isn't a `Future`, so you can use `Completer` to make it works in both cases.
> 
> You could try to change the code inside functionName.dart from
> ``` dart
> main() {
>   callbackToStream('onmessage', (html.MessageEvent e) {
>     return js_util.getProperty(e, 'data');
>   }).listen((message) async {
>     // TODO: Function for computation here
>     final result = await functionName(message);
> 
>     jsSendMessage(result);
>   });
> }
> ```
> to
> ``` dart
> main() {
>   callbackToStream('onmessage', (html.MessageEvent e) {
>     return js_util.getProperty(e, 'data');
>   }).listen((message) async {
>     // TODO: Function for computation here
>     final Completer completer = Completer();
>     completer.future.then((value) => jsSendMessage(value));
>     completer.complete(functionName(message));
>   });
> }
> ```

Thank you ❤️
