### ISSUE TITLE
Catching errors from isolate

### ISSUE THREAD

**Issue by xErik** [vursin/isolate_manager#4]
Hello, 

Is it possible to catch Exceptions thrown from within the Isolate?

The `try-catch` block does not get triggered.

```dart
import 'package:isolate_manager/isolate_manager.dart';

@pragma('vm:entry-point')
int add(dynamic value) {
  if (value[0] == 50) {
    throw 'No no no';
  }
  return value[0] + value[1];
}

main() async {
  final isolateManager = IsolateManager.create(add, concurrent: 2);
  await isolateManager.start();
  final List<Future> futures = [];

  try {
    for (var i = 0; i < 100; i++) {
      futures.add(isolateManager.compute([i, 20]));
    }

    await Future.wait(futures, eagerError: true);
  } catch (e) {
    print(e);
  } finally {
    isolateManager.stop();
  }
}
```

**Comment by vursin** [comment]
Hi,

The default isolate method using `.create` currently doesn't control the exception, you can try to create one with the `.createOwnIsolate`.

I'll keep this issue open as a to-do list that will be implemented in the next update. Thank you!

**Comment by vursin** [comment]
Hi @xErik,

I have released a preview version for this feature, you can try it by adding `isolate_manager: ^2.2.0-PRE.1` to your dependencies.

Please let me know the result. Thank you!

**Comment by vursin** [comment]
I have released this version to stable, so I'll mark this issue as resolved. Feel free to file an issue if you have any questions or problems.
